export interface Work {
  image: string;
}

const WORKS: Work[] = [
  { image: "2 pre.jpg" },
  { image: "3 rojo.jpg" },
  { image: "4 verde.jpg" },
  { image: "5 azul.jpg" },
  { image: "6 negro.jpg" },
  { image: "7 final.jpg" },
  { image: "c1.jpg" },
  { image: "c2.jpg" },
  { image: "c3.jpg" },
  { image: "c4.jpg" },
  { image: "c5.jpg" },
  { image: "c6.jpg" },
  { image: "E 0 b&w.jpg" },
  { image: "E 0.jpg" },
  { image: "E 1 b&w.jpg" },
  { image: "E 1.jpg" },
  { image: "E 2 b&w.jpg" },
  { image: "E 2.jpg" },
  { image: "E 3 b&w.jpg" },
  { image: "E 3.jpg" },
  { image: "E 4 b&w.jpg" },
  { image: "E 4.jpg" },
  { image: "E A 1.jpg" },
  { image: "E A.jpg" },
  { image: "eden 2.jpg" },
  { image: "eden 3.jpg" },
  { image: "eden 4.jpg" },
  { image: "eden 5.jpg" },
  { image: "fp.jpg" },
  { image: "fp4.jpg" },
  { image: "fpho.jpg" },
  { image: "fphot.jpg" },
  { image: "fpo.jpg" },
  { image: "lns.jpg" },
  { image: "mask.jpg" },
  { image: "pill 1.jpg" },
  { image: "pill.jpg" },
  { image: "post 4x3 1.jpg" },
  { image: "post 4x3 2.jpg" },
  { image: "TATTOO.jpg" },
  { image: "the dove 1.jpg" },
  { image: "the dove 2.jpg" },
  { image: "the dove 3 B&W fp.jpg" },
  { image: "the dove 3 B&W.jpg" },
  { image: "the dove 3 fp.jpg" },
  { image: "the dove 3.jpg" },
  { image: "the dove TATTO b&w fp.jpg" },
  { image: "the dove TATTO b&w.jpg" },
  { image: "the dove TATTO.jpg" },
  { image: "tree 2024 meaning I.jpg" },
  { image: "tree 2024.jpg" },
  { image: "tree b 3.jpg" },
  { image: "tree r 4.jpg" },
  { image: "tree v 3.jpg" },
  { image: "tres.jpg" },
  { image: "uno.jpg" },
];

export default WORKS;
